name: ${project.name}
version: ${project.version}
author: ${author}
main: ${project.groupId}.animalhunt.${project.name}
api-version: 1.13
commands:
  animalhunt:
    description: Base command
    usage: /<command> [reload|help]
permissions:
  animalhunt.help:
    description: Permission for the help command
  animalhunt.reload:
    description: Permission for the reload command
  animalhunt.butcher:
    description: Permission to butcher an animal